# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7514cfe1330832677ba1949d2fd9ed2e46b7a3a6f98b0d642e7017e4074a476e0e4c33ea78847fe33e3fdf4aa22769235bb91e7876f25ece85f13a605c7f889d

test:
  secret_key_base: c66e331a06874e5e59f1be4c7f5d232f5fb37a9f3aa51067a0f952b4523e927834ffee9c90c4229b64039d9787623c0d28773c566faf4445e5911eff485d4d1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
